OnlineSchedule/Controllers/AdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineSchedule.BusinessLogic.Mappers;
using OnlineSchedule.BusinessLogic.Services;
using OnlineSchedule.Data.Entities;
using OnlineSchedule.Presentation.ViewModels;

namespace OnlineSchedule.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminController : Controller 
    {
        private readonly UserService _userService;
        private readonly Mapper _mapper;

        public AdminController(UserService userService, Mapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var users = _userService.GetUsers();
            var models = _mapper.Map<List<UserShortDataViewModel>>(users);

            return View(models);
        }

        public IActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(CreateUserViewModel model)
        {
            if (ModelState.IsValid == false)
                return View(model);

            var user = _mapper.Map<User>(model);
            var result = await _userService.TryCreateUser(user, model.Password, model.Role);

            if (result.Succeeded)
            {
                var performer = _userService.GetUser(HttpContext.User);
                return RedirectToAction("Index");
            }

            AddErrors(result.Errors);
            return View(model);
        }


        private void AddErrors(IEnumerable<IdentityError> errors)
        {
            foreach (var item in errors)
                ModelState.AddModelError(string.Empty, item.Description);
        }
    }
}

OnlineSchedule/Controllers/AuthController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineSchedule.BusinessLogic.Authenticate;
using OnlineSchedule.Data.Entities;
using OnlineSchedule.Presentation.ViewModels;

namespace OnlineSchedule.Controllers
{
    public class AuthController : Controller 
    {
        private readonly Authenticator _authenticator;
        private readonly Mapper _mapper;

        public AuthController(Authenticator authenticator, Mapper mapper)
        {
            _authenticator = authenticator;
            _mapper = mapper;
        }

        public IActionResult Login()
        {
            if (_authenticator.IsAuthorized(HttpContext.User))
                return RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid == false)
                return View(model);

            var user = _mapper.Map<User>(model);

            var loginResult = _authenticator.TryLogin(user, model.Password, model.RememberMe);
            if (loginResult.Successfully == false)
            {
                SetModelStateErrors(loginResult.Errors);
                return View(model);
            }

            return RedirectToAction("All", "Schedule");
        }

        public IActionResult Registration()
        {
            if (_authenticator.IsAuthorized(HttpContext.User))
                return RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(RegistrationViewModel model)
        {
            if (ModelState.IsValid == false)
                return View(model);

            var user = _mapper.Map<User>(model);
            var registrationResult = _authenticator.TryRegistration(user, model.Password, model.RememberMe);
            if (registrationResult.Successfully == false)
            {
                SetModelStateErrors(registrationResult.Errors);
                return View(model);
            }

            return RedirectToAction("All", "Schedule");
        }

        public IActionResult Logout()
        {
            _authenticator.Logout();
            return RedirectToAction("Login");
        }

        public void SetModelStateErrors(IEnumerable<string> errors)
        {
            foreach (var error in errors)
            {
                ModelState.AddModelError(string.Empty, error);
            }
        }
    }
}

OnlineSchedule/Controllers/DayController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineSchedule.Controllers
{
    public class DayController : Controller
    {
        [HttpPost]
        public string Add(string scheduleId)
        {
            return $"all good, schedule id is {scheduleId}";
        }
    }
}

OnlineSchedule/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineSchedule.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineSchedule/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineSchedule.Controllers
{
    public class LessonController : Controller
    {
        [HttpPost]
        public string Add(string dayId)
        {
            return $"all good, lesson is added ::: dayId is {dayId}";
        }
    }
}

OnlineSchedule/Controllers/ModeratorController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineSchedule.Controllers
{
    public class ModeratorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineSchedule/Controllers/ScheduleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineSchedule.BusinessLogic.Services;
using OnlineSchedule.Data.Entities;
using OnlineSchedule.Data.Repositories.Interfaces;
using OnlineSchedule.Presentation.ViewModels;

namespace OnlineSchedule.Controllers 
{
    public class ScheduleController : Controller
    {
        private readonly IScheduleRepository _rep;
        private readonly Mapper _mapper;
        private readonly UserService _userService;

        public ScheduleController(IScheduleRepository rep, Mapper mapper, UserService userService)
        {
            _rep = rep;
            _mapper = mapper;
            _userService = userService;
        }

        public IActionResult Index(Guid id)
        {
            if (id == Guid.Empty)
                return View();

            Schedule schedule = _rep.Get(id);
            if (schedule == null)
                return NotFound(); 
            return View(schedule);
        }

        public IActionResult All()
        {
            var user = _userService.GetUser(HttpContext.User);
            var schedules = _rep.GetByUserId(user.Id);
            var models = _mapper.Map<List<ScheduleListItem>>(schedules);

            return View(models);
        }

        public IActionResult Add() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddScheduleViewModel model)
        {
            if (ModelState.IsValid == false)
                return View(model);

            var schedule = _mapper.Map<Schedule>(model);
            schedule.Id = Guid.NewGuid();

            _rep.Add(schedule);
            return RedirectToAction("Index", new { id = schedule.Id });
        }
    }
}

OnlineSchedule/Views/Admin/CreateUser.cshtml
@using Microsoft.AspNetCore.Identity;

@model OnlineSchedule.Presentation.ViewModels.CreateUserViewModel
@inject RoleManager<IdentityRole> _roleManager

<form action="CreateUser" method="post" class="form">
    <h1 class="title">Створити користувача</h1>
    
    <div class="input-group">
        <input asp-for="Email" type="text" class="input" placeholder="почта">
        <span asp-validation-for="Email"></span>
    </div>

    <div class="input-group">
        <input asp-for="Name" type="text" class="input" placeholder="ім'я користувача">
        <span asp-validation-for="Name"></span>
    </div>

    <div class="input-group">
        <input asp-for="Password" type="text" class="input" placeholder="пароль">
        <span asp-validation-for="Password"></span>
    </div>

    <div class="input-group">
        <input asp-for="ConfirmPassword" type="text" class="input" placeholder="повторіть пароль">
        <span asp-validation-for="ConfirmPassword"></span>
    </div>

    <select asp-for="Role" asp-items="new SelectList(_roleManager.Roles)" class="input"></select>

    <button class="btn btn-primary">створити</button>

    <div asp-validation-summary="ModelOnly"></div>

    @*<div class="form__error">якась помилка при створенні користувача</div>*@
</form>

OnlineSchedule/Views/Admin/Index.cshtml
@model IEnumerable<OnlineSchedule.Presentation.ViewModels.UserShortDataViewModel>

<div class="list__wrapper">
    <input type="text" class="input input-search input--hide" placeholder="пошук">
    <div class="main__header">
        <h1 class="title">Користувачі</h1>
        <div class="btn-group">
            <div class="btn btn-secondary search">пошук</div>
            <a asp-action="CreateUser" class="btn btn-secondary">створити користувача</a>
        </div>
    </div>
    
    <div class="list">
        @foreach(var user in Model)
        {
            <div class="list__item">
                <div>
                    ім’я користувача <br>
                    почта <br>
                    дата реєстрація <br>
                    роль <br>
                </div>
                <div class="list__data">
                    @user.Name <br>
                    @user.Email <br>
                    @user.DateOfRegistration <br>
                    @user.Role <br>

                    @*GineTik <br>
                    densheva18072003@gmail.com <br>
                    28.07.2022 <br>
                    адміністратор <br>*@
                </div>
                <div class="btn-group list__item-left">
                    <div class="btn btn-secondary">видалити</div>
                </div>
            </div>
        }
    </div>
</div>

OnlineSchedule/Views/History/Index.cshtml
<div class="list__wrapper">
    <div class="main__header">
        <h1 class="title">Історія</h1>
    </div>
    
    <div class="list">
        @for(int i = 0; i < 5; i++)
        {
            <div class="list__item">
                <div>
                    почта користувача <br>
                    почта виконавця <br>
                    дата видалення <br>
                    роль виконавця <br>
                    тип дії <br>
                </div>
                <div class="list__data">
                    destroer06@gmail.com <br>
                    densheva18072003@gmail.com <br>
                    28.07.2022 <br>
                    адміністратор <br>
                    видалення <br>
                </div>
                <div class="btn-group list__item-left">
                    <div class="btn btn-secondary">відновити</div>
                </div>
            </div>
        }

        @for(int i = 0; i < 5; i++)
        {
            <div class="list__item">
                <div>
                    назва розкладу <br>
                    почта виконавця <br>
                    дата видалення <br>
                    роль виконавця <br>
                    тип дії <br>
                </div>
                <div class="list__data">
                    якась назва розкладу <br>
                    densheva18072003@gmail.com <br>
                    28.07.2022 <br>
                    додавання <br>
                </div>
                <div class="btn-group list__item-left">
                    <div class="btn btn-secondary">видалити</div>
                </div>
            </div>
        }
    </div>
</div>

OnlineSchedule/Views/History/Schedules.cshtml
<div class="list__wrapper">
    <div class="main__header">
        <h1 class="title">Історія розкладів</h1>
    </div>
    
    <div class="list">
        @for(int i = 0; i < 5; i++)
        {
            <div class="list__item">
                <div>
                    почта користувача <br>
                    почта виконавця <br>
                    дата видалення <br>
                    роль виконавця <br>
                    тип дії <br>
                </div>
                <div class="list__data">
                    destroer06@gmail.com <br>
                    densheva18072003@gmail.com <br>
                    28.07.2022 <br>
                    адміністратор <br>
                    видалення <br>
                </div>
                <div class="btn-group list__item-left">
                    <div class="btn btn-secondary">відновити</div>
                </div>
            </div>
        }

        @for(int i = 0; i < 5; i++)
        {
            <div class="list__item">
                <div>
                    назва розкладу <br>
                    почта виконавця <br>
                    дата видалення <br>
                    роль виконавця <br>
                    тип дії <br>
                </div>
                <div class="list__data">
                    якась назва розкладу <br>
                    densheva18072003@gmail.com <br>
                    28.07.2022 <br>
                    додавання <br>
                </div>
                <div class="btn-group list__item-left">
                    <div class="btn btn-secondary">видалити</div>
                </div>
            </div>
        }
    </div>
</div>

OnlineSchedule/Views/History/Users.cshtml
<div class="list__wrapper">
    <div class="main__header">
        <h1 class="title">Історія аккаунтів</h1>
    </div>
    
    <div class="list">
        @foreach (var item in Model)
        {
            <div class="list__item">
                <div>
                    почта користувача <br>
                    почта виконавця <br>
                    дата видалення <br>
                    роль виконавця <br>
                    тип дії <br>
                </div>
                <div class="list__data">
                    @item.UserEmail <br>
                    @item.PerformerEmail <br>
                    @item.DateOfAction <br>
                    @item.PerformerRole <br>
                    @item.TypeOfAction

                    @*destroer06@gmail.com <br>
                    densheva18072003@gmail.com <br>
                    28.07.2022 <br>
                    адміністратор <br>
                    видалення <br>*@
                </div>
                <div class="btn-group list__item-left">
                    <div class="btn btn-secondary">відновити</div>
                </div>
            </div>
        }
    </div>
</div>

OnlineSchedule/Views/Home/Index.cshtml
Hello peoples

OnlineSchedule/Views/Moderator/Index.cshtml
<div class="list__wrapper">
    <div class="main__header">
        <h1 class="title">Скарги</h1>
    </div>
    
    <div class="list">
        @for(int i = 0; i < 5; i++)
        {
            <div class="list__item">
                <a asp-controller="Schedule" asp-action="Index" target="_blank"><h3 class="title link-dark">Назва розкладу</h3></a>
                <span class="list__item-left">скарг: <span class="text-danger">70</span></span>
                <div class="btn-group">
                    <div class="btn btn-secondary">залишити</div>
                    <div class="btn btn-secondary">видалити</div>
                </div>
            </div>
        }
    </div>
</div>

OnlineSchedule/Views/Schedule/Add.cshtml
@model OnlineSchedule.Presentation.ViewModels.AddScheduleViewModel

<form action="Add" class="form">
    <h1 class="title">Новий розклад</h1>
    <div class="input-group">
        <input asp-for="Title" type="text" class="input" placeholder="назва">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="input-group">
        <textarea asp-for="About" rows="5" class="input" placeholder="опис"></textarea>
        <span asp-validation-for="About" class="text-danger"></span>
    </div>

    <button class="btn btn-primary">створити</button>

    <div asp-validation-summary="ModelOnly"></div>

    @*<div class="form__error">якась помилка при створенні розкладу</div>*@
</form>

OnlineSchedule/Views/Schedule/All.cshtml
@model List<ScheduleListItem>

<div class="schedules">
    <div class="main__header">
        <h1 class="title">Мої розклади</h1>
    </div>
    <div class="list">
        @foreach (var item in Model)
        {
            <div class="list__item">
                <a asp-action="Index" asp-route-id="@item.Id"><h3 class="title link-dark">@item.Title</h3></a>
                <div class="btn-group list__item-left">
                    <div class="btn btn-secondary">видалити</div>
                </div>
            </div>
        }
    </div>
    <div class="schedules__btn">
        <a asp-action="Add" class="btn btn-primary">додати новий розклад</a>
    </div>
</div>

OnlineSchedule/Views/Schedule/Index.cshtml
<div class="main__header">
    <div class="editable-field title main__editable-field" contenteditable="">Назва проєкта</div>
    <div class="btn-group">
        <div class="btn btn-danger">поскаржитись</div>
        <div class="btn btn-secondary">викл. коментарі</div>
    </div>
    <div class="share">
        <a href="#" class="link share__link">https://www.google.com/</a>
        <div class="btn btn-secondary share__btn">копіювати</div>
    </div>
</div>


<div class="days">
@for(int i = 0; i < 3; i++)
{
    <table class="day table">
        <tr class="table__title">
            <td class="table__col" colspan="2">
                <div class="table__editable-field editable-field">Понеділок</div>
                <ion-icon class="btn-icon table__trash" name="trash-sharp"></ion-icon>
            </td>
        </tr>
        <tr class="table__row">
            <td class="table__col">
                <span class="table__editable-field editable-field" contenteditable>урок 1</span>
                <ion-icon class="btn-icon table__trash" name="trash-sharp"></ion-icon>
            </td>
            <td class="table__col">
                з <span class="table__editable-field editable-field">10:00</span>
                до <span class="table__editable-field editable-field">11:20</span>
            </td>
        </tr>

        <tr class="table__row">
            <td class="table__col">
                <span class="table__editable-field editable-field">урок 2</span>
                <ion-icon class="btn-icon table__trash" name="trash-sharp"></ion-icon>
            </td>
            <td class="table__col">
                з <span class="table__editable-field editable-field">11:35</span>
                до <span class="table__editable-field editable-field">12:50</span>
            </td>
        </tr>

        <tr class="table__row">
            <td class="table__col">
                <span class="table__editable-field editable-field">урок 3</span>
                <ion-icon class="btn-icon table__trash" name="trash-sharp"></ion-icon>
            </td>
            <td class="table__col">
                з <span class="table__editable-field editable-field">13:10</span>
                до <span class="table__editable-field editable-field">14:30</span>
            </td>
        </tr>

        <tr class="table__row">
            <td class="table__col">
                <span class="table__editable-field editable-field">останій урок</span>
                <ion-icon class="btn-icon table__trash" name="trash-sharp"></ion-icon>
            </td>
            <td class="table__col">
                з <span class="table__editable-field editable-field">14:40</span>
                до <span class="table__editable-field editable-field">16:00</span>
            </td>
        </tr>

        <tr class="table__row">
            <td class="table__col table__btn btn" colspan="2">
                додати новий рядок
            </td>
        </tr>
    </table>
}
</div>

<div class="about">
    <h1 class="title text-secondary about__title">Опис</h1>
    <p class="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu nisi a velit tempor porttitor eu et mi. Aenean tellus velit, commodo nec malesuada ut, placerat eget mi. Maecenas vestibulum nisi quis purus auctor fringilla. Nullam sodales risus porta, finibus felis cursus, vulputate justo. Pellentesque id egestas augue, quis accumsan odio. Nullam ornare tortor id tempor accumsan. Nam vel leo ipsum. Fusce ligula nisl, accumsan quis blandit vel, finibus at nunc. Nulla nec dolor ut urna eleifend semper. Mauris ipsum massa, semper vitae venenatis sed, dapibus at neque. Duis posuere ligula at odio hendrerit elementum. Curabitur nec urna nunc. In hac habitasse platea dictumst. Aenean id risus rutrum, bibendum nulla a, aliquet arcu.</p>
</div>

<div class="comments">
    <h1 class="title text-secondary comments__title">Коментарі</h1>
    <textarea rows="10" class="input" placeholder="пишіть..."></textarea>
    <button class="btn btn-primary">прокоментувати</button>

    <div class="comments__inner">
        @for(int i = 0; i < 5; i++) 
        {
            <div class="comments__item comment">
                <ion-icon class="comment__attach" name="attach-outline"></ion-icon>
                <div class="comment__content">
                    <div class="comment__header">
                        <a href="#" class="comment__author link text-primary">Ім’я користувача</a>
                        <div class="comment__date">28.07.2022</div>
                    </div>
                    <p class="text">Коментарь користувача</p>
                    <div class="reviews">
                        <div class="reviews__item">
                            <ion-icon name="thumbs-up-sharp"></ion-icon>
                            <span class="reviews__num">5</span>
                        </div>
                        <div class="reviews__item">
                            <ion-icon name="thumbs-up-sharp"></ion-icon>
                            <span class="reviews__num">0</span>
                        </div>
                    </div>
                </div>
                <div class="comment__btns btn-group">
                    <div class="btn btn-secondary">редагувати</div>
                    <div class="btn btn-secondary">видалити</div>
                    <div class="btn btn-secondary">закріпити</div>
                </div>
            </div>
        }
    </div>
</div>


@section Scripts {
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <script type="module">
        import { LessonService } from "./js/Services/LessonService.js";

        var lessons = new LessonService("@Url.Action("action", "controller")");
        $(".table__btn").click(function() {
            lessons.add(this.parentNode, "hjklasfdhjkasdflajshlf")
        });
    </script>
}

OnlineSchedule/Views/Shared/_Layout.cshtml
@inject OnlineSchedule.BusinessLogic.Authenticate.Authenticator _authenticator
@inject OnlineSchedule.BusinessLogic.Services.UserService _userService

<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OnlineSchedule - @ViewBag.Title</title>

    <link rel="stylesheet" href="~/styles/css/style.min.css">
    @RenderSection("Styles", required: false)
</head>
<body>
    <header class="header container">
        <a class="logo" href="~/">
            <h3 class="title">Schedule<br>Online</h3>
        </a>
        <nav class="navbar header__navbar">
            <a asp-controller="Home" asp-action="Index" class="navbar__item navbar__item--active">Головна</a>
            
            @if (_userService.GetUser(Context.User) != null)
            {
                <a asp-controller="Schedule" asp-action="All" class="navbar__item">Мої розклади</a>
            }

            @if (_userService.ExistsRole(Context.User, "Moderator, Admin"))
            {
                <a asp-controller="Moderator" asp-action="Index" class="navbar__item">Для модератора</a>
            }

            @if (_userService.ExistsRole(Context.User, "Admin"))
            {
                <a asp-controller="Admin" asp-action="Index" class="navbar__item">Для адміністратора</a>
            }
        </nav>
        <div class="account btn-group header__account">

            @if (_authenticator.IsAuthorized(Context.User) == false)
            {
                <a asp-controller="Auth" asp-action="Login" class="btn btn-secondary">вхід</a>
                <a asp-controller="Auth" asp-action="Registration" class="btn btn-primary">реєстрація</a>
            }
            else
            {
                <div class="btn btn-primary">@Context.User.Identity.Name</div>
                <a asp-controller="Auth" asp-action="Logout" class="btn btn-secondary">вихід</a>
            }
        </div>
    </header>

    <main class="main container">
        @RenderBody()
    </main>

    @*Jquery*@
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>